name: GCC Build/Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gcc:
    uses: ./.github/workflows/cmake-reusable.yml
    with:
      os: ubuntu-latest
      c_compiler: gcc
      cxx_compiler: g++
      build_dir_name: build-gcc
